export const PROJECTS_DATA = [
  {
    title: "K-SOX AI",
    description: "React와 Next.js로 구축한 K-SOX AI 웹 앱",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Next.js", "Typescript", "Tailwind", "React-query", "Zustand"],
    github: "#",
    demo: "#",
    star_rate: 5,
  },
  {
    title: "Devkit",
    description:
      "자사 서비스 디자인의 통일성 및 프론트엔드 개발 생산성 증가를 위해 구축한 사내 디자인 시스템 ",
    image: "/placeholder.svg?height=200&width=300",
    tags: [
      "Next.js",
      "TypeScript",
      "Storybook",
      "Tailwind",
      "Chromatic",
      "Rollup",
      "Figma",
    ],
    github: "#",
    demo: "#",
    star_rate: 5,
  },
  {
    title: "Dofarming",
    description: "",
    image: "/placeholder.svg?height=200&width=300",
    tags: [
      "Next.js",
      "KakaoAPI",
      "Tailwind",
      "Styled-components",
      "React-query",
    ],
    github: "https://github.com/goorm-dofarming/Frontend",
    demo: "#",
    star_rate: 4,
  },
  {
    title: "Algorithm Fighter",
    description:
      "게임방 생성 및 실시간 채팅 기능과 알고리즘 풀이 1:1 대결 기능을 가진 게임 웹서비스",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Next.js", "Tailwind", "Stomp.js"],
    github: "https://github.com/gooormmoon/algorithm-fighter-front",
    demo: "#",
    star_rate: 4,
  },
  {
    title: "Social Media App",
    description: "실시간 채팅과 피드 기능을 가진 소셜 미디어 앱",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["React Native", "Socket.io", "Node.js"],
    github: "#",
    demo: "#",
    star_rate: 3,
  },
  {
    title: "Learning Platform",
    description: "온라인 강의와 퀴즈 기능을 제공하는 학습 플랫폼",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["React", "Redux", "Express", "MongoDB"],
    github: "#",
    demo: "#",
    star_rate: 2,
  },
];
